### ISSUE TITLE
Add StyleCI Support

### ISSUE THREAD

**Issue by vinkla** [ivanakimov/hashids.php#56]
What about adding https://styleci.io/ support? Then we will get syntax checks on all commits and PRs made to this repository. It can even fix all syntax errors automagically.

This is the guide to add StyleCI support:

1. Sign up at https://styleci.io/
2. Go to the repositories page https://styleci.io/account#repos
3. Enable this repository.
4. Press **Show Analysis** and then **Settings**.
5. Add the following settings:
    ```yml
enabled:
  - unalign_double_arrow

disabled:
  - align_double_arrow
  - phpdoc_align
    ```
6. Press **Save Configuration**.
7. Press **Analyze Now**. 

This has to be done by the owner of the repository.
